name: PyTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - uses: ouzi-dev/commit-status-updater@v1.1.0 # Updates the commit status badge to pending

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-sphinx pytest-cov mypy==0.960 tqdm PyGithub attrs
        pip list
    - name: Test with pytest
      run: |
        pytest tests
    - if: always() # Updates the commit status badge to the result of running the tests above
      uses: ouzi-dev/commit-status-updater@v1.1.0
      with:
        status: "${{ job.status }}"